---

# Install PIP
- name: Install python pip
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ python_pip }}"

- name: Upgrade PIP
  pip:
    name: pip
    state: latest

- name: Install pkgs
  pip:
    name: "{{ item }}"
    state: latest
  loop: "{{ pip_pkgs }}"
