---

- name: Gather package facts
  package_facts:
      manager: "auto"

- name: Install yum Group dependencies
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ yum_group }}"

- name: Install yum dependencies
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ yum_pkgs }}"

- name: Download, Configure and Install OVS
  when: "'openvswitch' not in ansible_facts.packages or ansible_facts.packages.openvswitch[0].version != ovs_ver"
  block:
    - name: Download source OVS
      get_url:
        url: "{{ ovs_link }}"
        dest: /root/
      
    - name: Unarchive source
      unarchive:
          src: /root/openvswitch-{{ ovs_ver }}.tar.gz
          dest: /root/
          remote_src: yes
    - name: Create rpmbuild directory
      file:
        path: /root/rpmbuild/SOURCES
        state: directory
    
    - name: Copy OVS {{ ovs_ver }} Source to rpmbuild
      copy:
        src: /root/openvswitch-{{ ovs_ver }}.tar.gz
        dest: /root/rpmbuild/SOURCES/
        remote_src: yes

    - name: Build OVS {{ ovs_ver }} RPM
      shell: "rpmbuild -bb rhel/openvswitch-fedora.spec"
      args:
        chdir: "/root/openvswitch-{{ ovs_ver }}"

    - name: Install OVS {{ ovs_ver }}
      yum:
        name: /root/rpmbuild/RPMS/x86_64/openvswitch-{{ ovs_ver }}-1.el7.x86_64.rpm
        state: present
    
    - name: Enable and Start OpenVSwitch Service
      service:
        name: openvswitch
        state: started
        enabled: yes
        