- name: Install Docker Dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ yum_pkgs }}"

- name: Install Docker-CE Repo
  shell: "yum-config-manager --add-repo {{ docker_yum_repo }}"

- name: Install Docker-CE
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_yum_pkgs }}"

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add users to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  notify: reboot host

- name: Enable and Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker PIP libraries
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  loop: "{{ docker_pip }}"

- name: run handlers immediately
  meta: flush_handlers
    